version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: mvn clean install -Dmaven.test.skip=true
    - run: 
        command: |
           TEST=$(circleci tests glob "integration-tests/src/test/groovy/com/okta/sdk/tests/it/**IT.groovy" | circleci tests split --split-by=timings)
           mvn -Dtest=$TEST test
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*
    - store_test_results:
        path: ~/mvn-test-results

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0-node
    parallelism: 10
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0-node
    parallelism: 10
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  build_and_test:
    jobs:
      - jdk8
      - jdk11
