version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: ./mvnw clean install -Pci
    - run:
        when: on_fail
        command: cat $(circleci tests glob "integration-tests/target/failsafe-reports/*IT.txt" | circleci tests split --split-by=timings)
    - run:
        when: on_fail
        command: cat $(circleci tests glob "integration-tests/target/failsafe-reports/*dump*" | circleci tests split --split-by=timings)

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0-node
    parallelism: 10
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0-node
    parallelism: 10
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  build_and_test:
    jobs:
      - jdk8
      - jdk11
