version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: circleci tests glob "integration-tests/src/test/groovy/com/okta/sdk/tests/it/**IT.groovy" | circleci tests split --split-by=timings
    - run: mvn clean install -Dmaven.test.skip=true
    - run:
        command: |
          cd ./integration-tests
          mvn -Dtest=DomainIT,IdpIT test
    - run: pwd
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0-node
    environment:
        JVM_OPTS: -Xmx3200m
    parallelism: 4
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0-node
    environment:
        JVM_OPTS: -Xmx3200m
    parallelism: 4
    steps: *build_steps

workflows:
  build_and_test:
    jobs:
      - jdk8
      - jdk11
